/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background:               '#09090B',
        surface:                  '#131315',
        'surface-dim':            '#131315',
        'surface-bright':         '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low':  '#1c1b1d',
        'surface-container':      '#201f22',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'surface-variant':        '#353437',
        'surface-tint':           '#ddb7ff',
        'on-surface':             '#e5e1e4',
        'on-surface-variant':     '#cfc2d6',
        'inverse-surface':        '#e5e1e4',
        'inverse-on-surface':     '#313032',
        outline:                  '#988d9f',
        'outline-variant':        '#4d4354',
        primary:                  '#ddb7ff',
        'on-primary':             '#490080',
        'primary-container':      '#b76dff',
        'on-primary-container':   '#400071',
        'inverse-primary':        '#842bd2',
        'primary-fixed':          '#f0dbff',
        'primary-fixed-dim':      '#ddb7ff',
        'on-primary-fixed':       '#2c0051',
        'on-primary-fixed-variant': '#6900b3',
        secondary:                '#c0c1ff',
        'on-secondary':           '#1000a9',
        'secondary-container':    '#3131c0',
        'on-secondary-container': '#b0b2ff',
        'secondary-fixed':        '#e1e0ff',
        'secondary-fixed-dim':    '#c0c1ff',
        'on-secondary-fixed':     '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        tertiary:                 '#3cddc7',
        'on-tertiary':            '#003731',
        'tertiary-container':     '#00a392',
        'on-tertiary-container':  '#00302a',
        'tertiary-fixed':         '#62fae3',
        'tertiary-fixed-dim':     '#3cddc7',
        'on-tertiary-fixed':      '#00201c',
        'on-tertiary-fixed-variant': '#005047',
        error:                    '#ffb4ab',
        'on-error':               '#690005',
        'error-container':        '#93000a',
        'on-error-container':     '#ffdad6',
      },
      fontFamily: {
        sans:  ['Manrope', 'sans-serif'],
        mono:  ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:     '0.25rem',
        md:     '0.75rem',
        lg:     '1rem',
        xl:     '1.5rem',
        '2xl':  '1rem',
        '3xl':  '1.5rem',
        full:   '9999px',
      },
      spacing: {
        'container-max': '1440px',
        base:            '8px',
        gutter:          '24px',
        'margin-mobile': '20px',
        'margin-desktop': '48px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
      },
      keyframes: {
        fadeInUp: {
          '0%':   { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
