const Groq = require('groq-sdk');
const mongoose = require('mongoose');
const Playlist = require('../models/Playlist');
const mockDb = require('../services/mockDb');
const youtubeService = require('../services/youtubeService');

// Helper: get a configured Groq client
function getGroqClient() {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
        throw new Error('GROQ_API_KEY is not configured in the server environment.');
    }
    return new Groq({ apiKey });
}

// Helper: parse JSON safely from model output (strip markdown fences if present)
function parseJsonResponse(text) {
    let cleaned = (text || '').trim();
    if (cleaned.startsWith('```')) {
        cleaned = cleaned.replace(/^```(json)?/, '').replace(/```$/, '').trim();
    }
    const parsed = JSON.parse(cleaned);
    if (!Array.isArray(parsed)) throw new Error('Response is not an array');
    return parsed;
}

const generatePlaylist = async (req, res) => {
    try {
        const { prompt, count = 10, isPublic = false, title } = req.body;
        const userId = req.user._id;

        if (!prompt) {
            return res.status(400).json({ error: 'Prompt is required' });
        }

        const groq = getGroqClient();

        // 1. Call Groq API (llama-3.3-70b-versatile — free tier)
        const completion = await groq.chat.completions.create({
            model: 'llama-3.3-70b-versatile',
            messages: [
                {
                    role: 'system',
                    content: `You are an expert music curator. Generate exactly ${count} songs that perfectly match the user's prompt.
You must return ONLY a valid JSON array of objects, each with exactly two string properties: "title" and "artist".
Do not wrap the JSON in markdown code blocks. Output raw JSON only.`
                },
                {
                    role: 'user',
                    content: `Generate ${count} songs for this vibe/mood: "${prompt}"`
                }
            ],
            temperature: 0.8,
            max_tokens: 2048,
            response_format: { type: 'json_object' }
        });

        const rawText = completion.choices[0]?.message?.content || '';

        let aiSongs = [];
        try {
            // Groq json_object mode wraps in an object — handle both array and wrapped
            const parsed = JSON.parse(rawText);
            if (Array.isArray(parsed)) {
                aiSongs = parsed;
            } else {
                // Find the first array value in the object
                const firstArray = Object.values(parsed).find(v => Array.isArray(v));
                if (firstArray) aiSongs = firstArray;
                else throw new Error('No array found in response');
            }
        } catch (e) {
            console.error('Failed to parse Groq response:', rawText);
            return res.status(500).json({ error: 'Failed to parse AI response' });
        }

        // 2. Map AI songs to YouTube results
        const playlistSongs = [];
        for (const aiSong of aiSongs) {
            try {
                const query = `${aiSong.title} ${aiSong.artist} official audio`;
                const searchResults = await youtubeService.searchMusic(query);
                if (searchResults && searchResults.length > 0) {
                    playlistSongs.push(searchResults[0]);
                }
            } catch (err) {
                console.warn(`Failed to fetch YouTube details for ${aiSong.title} by ${aiSong.artist}`);
            }
        }

        if (playlistSongs.length === 0) {
            console.warn('No songs resolved, falling back to trending music...');
            try {
                const trending = await youtubeService.getTrendingMusic();
                playlistSongs.push(...trending.slice(0, count));
            } catch (err) {
                return res.status(500).json({ error: 'Failed to find any playable songs for this prompt' });
            }
        }

        // 3. Create Playlist in MongoDB
        const playlistName = title || `AI Playlist: ${prompt.slice(0, 30)}${prompt.length > 30 ? '...' : ''}`;
        const description = `Generated by Melodia AI. Prompt: "${prompt}"`;
        const coverImage = playlistSongs[0]?.thumbnail || '';

        let savedPlaylist;
        if (mongoose.connection.readyState === 1) {
            const newPlaylist = new Playlist({
                owner: userId,
                title: playlistName,
                description,
                isPublic: isPublic,
                songs: playlistSongs,
                coverImage,
                playlistType: 'ai',
                isAIGenerated: true
            });
            savedPlaylist = await newPlaylist.save();
        } else {
            savedPlaylist = mockDb.createPlaylist(userId, {
                title: playlistName,
                description,
                isPublic,
                songs: playlistSongs,
                coverImage,
                playlistType: 'ai',
                isAIGenerated: true
            });
        }

        res.status(201).json(savedPlaylist);
    } catch (error) {
        console.error('Error generating smart playlist:', error);
        res.status(500).json({ error: error.message || 'Internal server error while generating playlist' });
    }
};

const getAutoplayRecommendations = async (req, res) => {
    try {
        const { title, artist } = req.body;
        if (!title) {
            return res.status(400).json({ error: 'Title is required for autoplay context' });
        }

        const groq = getGroqClient();

        const completion = await groq.chat.completions.create({
            model: 'llama-3.3-70b-versatile',
            messages: [
                {
                    role: 'system',
                    content: `You are a music recommendation engine.
Return ONLY a valid JSON array of exactly 5 songs similar to the requested track.
Each object must have exactly two string properties: "title" and "artist".
Do not wrap the JSON in markdown code blocks. Output raw JSON array only.`
                },
                {
                    role: 'user',
                    content: `Recommend 5 songs similar to "${title}" by "${artist || 'Unknown Artist'}".`
                }
            ],
            temperature: 0.8,
            max_tokens: 512
        });

        const rawText = completion.choices[0]?.message?.content || '';

        let aiSongs = [];
        try {
            aiSongs = parseJsonResponse(rawText);
        } catch (e) {
            console.error('Failed to parse Groq autoplay response:', rawText);
            return res.status(500).json({ error: 'Failed to parse recommendations' });
        }

        const resolvedSongs = [];
        for (const aiSong of aiSongs) {
            try {
                const query = `${aiSong.title} ${aiSong.artist} official audio`;
                const searchResults = await youtubeService.searchMusic(query);
                if (searchResults && searchResults.length > 0) {
                    resolvedSongs.push({
                        id: searchResults[0].id,
                        videoId: searchResults[0].videoId,
                        title: searchResults[0].title,
                        artist: searchResults[0].artist,
                        thumbnail: searchResults[0].thumbnail,
                        duration: searchResults[0].duration
                    });
                }
            } catch (err) {
                console.warn(`Autoplay YouTube resolution failed for ${aiSong.title}`);
            }
        }

        res.status(200).json(resolvedSongs);
    } catch (error) {
        console.error('Error generating autoplay recommendations:', error);
        res.status(500).json({ error: 'Failed to generate recommendations' });
    }
};

const getLyrics = async (req, res) => {
    try {
        const { title, artist } = req.body;
        if (!title) {
            return res.status(400).json({ error: 'Title parameter is required' });
        }

        const groq = getGroqClient();

        const completion = await groq.chat.completions.create({
            model: 'llama-3.3-70b-versatile',
            messages: [
                {
                    role: 'system',
                    content: `You are a lyrics database. Return ONLY the clean text lyrics of the song requested.
Do not add introductions, explanations, headings, metadata, credits, or markdown. Just the raw lyrics text with line breaks.`
                },
                {
                    role: 'user',
                    content: `Provide the full lyrics for "${title}" by "${artist || 'Unknown Artist'}".`
                }
            ],
            temperature: 0.2,
            max_tokens: 2048
        });

        const lyrics = completion.choices[0]?.message?.content || 'Lyrics not found.';
        res.status(200).json({ lyrics });
    } catch (error) {
        console.error('Error fetching lyrics:', error);
        res.status(500).json({ error: 'Failed to fetch lyrics' });
    }
};

const CACHED_TRENDING_SONGS = [
    { videoId: 'kJQP7kiw5Fk', title: 'Despacito', artist: 'Luis Fonsi ft. Daddy Yankee', thumbnail: 'https://img.youtube.com/vi/kJQP7kiw5Fk/0.jpg', duration: '4:41' },
    { videoId: '9bZkp7q19f0', title: 'Gangnam Style', artist: 'PSY', thumbnail: 'https://img.youtube.com/vi/9bZkp7q19f0/0.jpg', duration: '4:12' },
    { videoId: '09R8_2nJtjg', title: 'Sugar', artist: 'Maroon 5', thumbnail: 'https://img.youtube.com/vi/09R8_2nJtjg/0.jpg', duration: '5:01' },
    { videoId: 'OPf0YbXqDm0', title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', thumbnail: 'https://img.youtube.com/vi/OPf0YbXqDm0/0.jpg', duration: '4:30' },
    { videoId: 'YQHsXMglC9A', title: 'Hello', artist: 'Adele', thumbnail: 'https://img.youtube.com/vi/YQHsXMglC9A/0.jpg', duration: '6:06' },
    { videoId: 'JGwWNGJdvx8', title: 'Shape of You', artist: 'Ed Sheeran', thumbnail: 'https://img.youtube.com/vi/JGwWNGJdvx8/0.jpg', duration: '4:23' },
    { videoId: 'fKopy74wq5I', title: 'I Love It', artist: 'Icona Pop', thumbnail: 'https://img.youtube.com/vi/fKopy74wq5I/0.jpg', duration: '2:59' },
    { videoId: 'ktvTqknDobU', title: 'Radioactive', artist: 'Imagine Dragons', thumbnail: 'https://img.youtube.com/vi/ktvTqknDobU/0.jpg', duration: '4:21' },
    { videoId: 'hT_nvWreIhg', title: 'Counting Stars', artist: 'OneRepublic', thumbnail: 'https://img.youtube.com/vi/hT_nvWreIhg/0.jpg', duration: '4:43' },
    { videoId: 'rYEDA3JcQqw', title: 'Rolling in the Deep', artist: 'Adele', thumbnail: 'https://img.youtube.com/vi/rYEDA3JcQqw/0.jpg', duration: '3:53' },
    { videoId: 'pRpeEdMmmQ0', title: 'Waka Waka (This Time for Africa)', artist: 'Shakira', thumbnail: 'https://img.youtube.com/vi/pRpeEdMmmQ0/0.jpg', duration: '3:30' },
    { videoId: 'LJHyoV9584U', title: 'Love Me Like You Do', artist: 'Ellie Goulding', thumbnail: 'https://img.youtube.com/vi/LJHyoV9584U/0.jpg', duration: '4:12' },
    { videoId: '7PCkvCPvDXk', title: 'Lean On', artist: 'Major Lazer & DJ Snake', thumbnail: 'https://img.youtube.com/vi/7PCkvCPvDXk/0.jpg', duration: '2:58' },
    { videoId: '1G4isv_Fylg', title: 'Closer', artist: 'The Chainsmokers ft. Halsey', thumbnail: 'https://img.youtube.com/vi/1G4isv_Fylg/0.jpg', duration: '4:05' },
    { videoId: 'papuvlVeTyI', title: 'Wake Me Up', artist: 'Avicii', thumbnail: 'https://img.youtube.com/vi/papuvlVeTyI/0.jpg', duration: '4:32' },
    { videoId: 'HMUDVMiFNrc', title: 'Stressed Out', artist: 'Twenty One Pilots', thumbnail: 'https://img.youtube.com/vi/HMUDVMiFNrc/0.jpg', duration: '3:45' },
    { videoId: 'UqyT8IEB14s', title: 'Stay', artist: 'The Kid LAROI & Justin Bieber', thumbnail: 'https://img.youtube.com/vi/UqyT8IEB14s/0.jpg', duration: '2:21' },
    { videoId: 'DyDfgMOUjCI', title: 'Blinding Lights', artist: 'The Weeknd', thumbnail: 'https://img.youtube.com/vi/DyDfgMOUjCI/0.jpg', duration: '3:21' },
    { videoId: 'fLexgOxsZu0', title: 'Bad Guy', artist: 'Billie Eilish', thumbnail: 'https://img.youtube.com/vi/fLexgOxsZu0/0.jpg', duration: '3:14' },
    { videoId: 'gdZLi9oWNZg', title: 'Dynamite', artist: 'BTS', thumbnail: 'https://img.youtube.com/vi/gdZLi9oWNZg/0.jpg', duration: '3:43' }
];

const generateDiscoverWeekly = async (req, res) => {
    try {
        const userId = req.user._id;
        
        let likedSongs = [];
        let playlists = [];
        
        if (mongoose.connection.readyState === 1) {
            const User = require('../models/User');
            const userObj = await User.findById(userId);
            likedSongs = userObj?.likedSongs || [];
            playlists = await Playlist.find({ owner: userId });
        } else {
            const userObj = mockDb.getUser(req.user.firebaseUid || req.user._id);
            likedSongs = userObj?.likedSongs || [];
            playlists = mockDb.getPlaylists(userId);
        }

        const likedSongList = likedSongs.map(s => `"${s.title}" by ${s.artist}`).join(', ');
        
        const genres = [];
        const tags = [];
        const artistCounts = {};
        
        likedSongs.forEach(s => {
            if (s.artist) {
                artistCounts[s.artist] = (artistCounts[s.artist] || 0) + 1;
            }
        });

        playlists.forEach(p => {
            if (p.genre) genres.push(p.genre);
            if (p.tags) tags.push(...p.tags);
            p.songs?.forEach(s => {
                const artist = s.artist || s.channelTitle;
                if (artist) {
                    artistCounts[artist] = (artistCounts[artist] || 0) + 1;
                }
            });
        });

        const favoriteArtists = Object.entries(artistCounts)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5)
            .map(entry => entry[0])
            .join(', ');

        const favoriteGenres = [...new Set(genres)].slice(0, 3).join(', ');
        const favoriteTags = [...new Set(tags)].slice(0, 5).join(', ');

        let promptText = '';
        const hasHistory = likedSongs.length > 0 || playlists.length > 0;
        
        if (hasHistory) {
            promptText = `Based on this user's music profile:
- Liked Songs: ${likedSongList.slice(0, 1000)}
- Favorite Artists: ${favoriteArtists}
- Favorite Genres: ${favoriteGenres}
- Mood Tags: ${favoriteTags}

Recommend exactly 20 songs they are most likely to enjoy. The songs should be fresh, diverse, and align with their taste.
Do not recommend songs they already like. Return ONLY a valid JSON array of objects, each with exactly two string properties: "title" and "artist".
Do not wrap the JSON in markdown code blocks. Output raw JSON only.`;
        } else {
            promptText = `Recommend exactly 20 popular and trending hit songs across diverse genres.
Return ONLY a valid JSON array of objects, each with exactly two string properties: "title" and "artist".
Do not wrap the JSON in markdown code blocks. Output raw JSON only.`;
        }

        let aiSongs = [];
        let geminiError = false;
        try {
            const { GoogleGenAI } = require('@google/genai');
            const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
            
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: promptText,
                config: {
                    responseMimeType: 'application/json',
                    responseSchema: {
                        type: 'ARRAY',
                        items: {
                            type: 'OBJECT',
                            properties: {
                                title: { type: 'STRING' },
                                artist: { type: 'STRING' }
                            },
                            required: ['title', 'artist']
                        }
                    }
                }
            });
            const text = response.text || '';
            aiSongs = JSON.parse(text);
        } catch (err) {
            console.error('Gemini Discover Weekly recommendation failed, using fallback:', err);
            geminiError = true;
        }

        let playlistSongs = [];
        if (!geminiError && aiSongs.length > 0) {
            for (const aiSong of aiSongs) {
                try {
                    const query = `${aiSong.title} ${aiSong.artist} official audio`;
                    const searchResults = await youtubeService.searchMusic(query);
                    if (searchResults && searchResults.length > 0) {
                        playlistSongs.push(searchResults[0]);
                    }
                } catch (err) {
                    console.warn(`YouTube search failed for Discover Weekly track: ${aiSong.title}`);
                }
            }
        }

        if (playlistSongs.length < 5) {
            console.warn('Resolving with trending music fallback...');
            try {
                const trending = await youtubeService.getTrendingMusic();
                playlistSongs = trending.slice(0, 20);
            } catch (err) {
                console.warn('YouTube trending failed, using cached trending fallback...');
                playlistSongs = CACHED_TRENDING_SONGS;
            }
        }

        if (playlistSongs.length > 20) {
            playlistSongs = playlistSongs.slice(0, 20);
        }

        const title = 'Discover Weekly';
        const description = 'Your weekly mixtape of fresh music, customized to your taste. Generated by Melodia AI.';
        const coverImage = playlistSongs[0]?.thumbnail || 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=500';

        let discoverPlaylist;
        if (mongoose.connection.readyState === 1) {
            discoverPlaylist = await Playlist.findOne({ owner: userId, title: 'Discover Weekly' });
            if (discoverPlaylist) {
                discoverPlaylist.songs = playlistSongs;
                discoverPlaylist.coverImage = coverImage;
                discoverPlaylist.description = description;
                discoverPlaylist.playlistType = 'ai';
                discoverPlaylist.isAIGenerated = true;
                await discoverPlaylist.save();
            } else {
                discoverPlaylist = new Playlist({
                    owner: userId,
                    title,
                    description,
                    songs: playlistSongs,
                    coverImage,
                    privacy: 'Private',
                    playlistType: 'ai',
                    isAIGenerated: true
                });
                await discoverPlaylist.save();
            }
        } else {
            const allMockPlaylists = mockDb.getPlaylists(userId);
            discoverPlaylist = allMockPlaylists.find(p => p.title === 'Discover Weekly');
            if (discoverPlaylist) {
                discoverPlaylist.songs = playlistSongs;
                discoverPlaylist.coverImage = coverImage;
                discoverPlaylist.description = description;
                discoverPlaylist.playlistType = 'ai';
                discoverPlaylist.isAIGenerated = true;
                await discoverPlaylist.save();
            } else {
                discoverPlaylist = mockDb.createPlaylist(userId, {
                    title,
                    description,
                    songs: playlistSongs,
                    coverImage,
                    privacy: 'Private',
                    playlistType: 'ai',
                    isAIGenerated: true
                });
            }
        }

        res.status(200).json({ success: true, playlist: discoverPlaylist });
    } catch (error) {
        console.error('Error generating discover weekly playlist:', error);
        res.status(500).json({ error: error.message || 'Failed to generate Discover Weekly' });
    }
};

module.exports = {
    generatePlaylist,
    getAutoplayRecommendations,
    getLyrics,
    generateDiscoverWeekly
};
